FROM ubuntu:rolling as build
                
ARG BUILD_DEPS="\
    ca-certificates \
    clang \
    gcc \
    git \
    libmp3lame-dev \
    libfdk-aac-dev \
    libogg-dev \
    libtool \
    libva-dev \
    libvorbis-dev \
    libzimg-dev \
    make \
    nasm \
    ocl-icd-opencl-dev \
    libx264-dev \
    libx265-dev \
    yasm \
    zlib1g-dev \
"
                
ARG FFMPEG_CONFIG="\
    --disable-debug \
    --enable-pic \
    --enable-gpl \
    --enable-nonfree \
    --disable-doc \
    --disable-htmlpages \
    --disable-manpages \
    --disable-podpages \
    --disable-txtpages \
    --disable-indevs \
    --disable-outdevs \
    --enable-vaapi \
    --disable-alsa \
    --disable-appkit \
    --disable-avfoundation \
    --disable-bzlib \
    --disable-coreimage \
    --disable-iconv \
    --enable-libfdk-aac \
    --enable-libmp3lame \
    --enable-libvorbis \
    --enable-libx264 \
    --enable-libx265 \
    --disable-lzma \
    --enable-opencl \
    --disable-sndio \
    --disable-schannel \
    --disable-sdl2 \
    --disable-securetransport \
    --disable-xlib \
    --enable-libzimg \
    --disable-zlib \
    --enable-cuda-llvm \
    --enable-nvenc \
"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y --no-install-recommends ${BUILD_DEPS}
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /

# Clone source code
RUN git clone https://github.com/FFmpeg/nv-codec-headers.git -b n12.0.16.0
RUN git clone https://github.com/FFmpeg/FFmpeg.git -b n6.0

# Build nv-codec-headers
WORKDIR /nv-codec-headers
RUN make -j$(nproc) install

# Build FFmpeg
WORKDIR /FFmpeg
RUN ./configure ${FFMPEG_CONFIG} && make -j$(nproc) install

FROM ubuntu:rolling

ARG DEPS="\
    default-jdk \
    intel-opencl-icd \
    libmp3lame0 \
    libfdk-aac2 \
    libogg0 \
    libva2 \
    libvorbis0a \
    libzimg2 \
    maven \
    ocl-icd-libopencl1 \
    x264 \
    x265 \
    zlib1g \
"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y --no-install-recommends ${DEPS}
RUN rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility,video

COPY --from=build /usr/local/bin/* /usr/local/bin/
COPY --from=build /usr/local/lib/*.a /usr/local/lib/

EXPOSE 1556
